services:
  - type: web
    name: shl-recommender
    env: python
    region: oregon
    plan: free
    buildCommand: "cd app && pip install -r requirements.txt"
    startCommand: "cd app && uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DATA_PATH
        value: ../data/individual-assessment.json
